lexik_translation:
  fallback_locale: [en]         # (required) default locale(s) to use
  managed_locales: [en, fr, de] # (required) locales that the bundle has to manage
  storage:
    type: orm                  # orm | mongodb | propel
    object_manager: default
  base_layout: "LexikTranslationBundle::layout.html.twig"