#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_security_check:
  path: /login_check
  controller: FOS\UserBundle\Controller\SecurityController::check
  methods: ["POST"]
  options:
    expose: true